<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.0.11 INSTALLER - Tuesday 27th of March 2012 01:39:20 AM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | https://github.com/hybridauth/hybridauth
*  (c) 2009-2011 HybridAuth authors | hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" => "http://localhost/hybridauth/hybridauth/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"Yahoo" => array ( 
				"enabled" => true 
			),

			"AOL"  => array ( 
				"enabled" => true 
			),

			"Google" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ),
				"scope"   => ""
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( 
									"id" => "113906752042186",
									"secret" => "e95a6804222ca5901f93dbc00f333c2b" 
									),

				// A comma-separated list of permissions you want to request from the user. See the Facebook docs for a full list of available permissions: http://developers.facebook.com/docs/reference/api/permissions.
				"scope"   => "", 

				// The display context to show the authentication page. Options are: page, popup, iframe, touch and wap. Read the Facebook docs for more details: http://developers.facebook.com/docs/reference/dialogs#display. Default: page
				"display" => "" 
			),
			"QQ" 	=> ARRAY (
					"enabled" 	=> TRUE,
					"keys"	 	=> ARRAY (
							"key" 	  => "801110090",
							"secret" => "f3e7a815ebfc46a08f4b08714718d4e7",
					),
					"wrapper" 	=> "Providers/qq.php",
					"icon"		=> "login_003"
			),
			"Sina" => array (
					"enabled" => true,
					"keys"    => array (
							"key" => "1434420599",//"3502523468",
							"secret" => "990e16a560409bf6156589ac6492fe4c",//"6d0a90267968ecdd99c277135843e371"
					)
			),
			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( 
									"key" => "27839422-2fHaNJZwmXZEKmzCzV7AmUcqau9SmkwqyusBdz4pw",
									"secret" => "MdHgTSzHhjgEDdCtGM42veAHwLS3vW8mXGdKUhgY" 
									) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"Foursquare" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => "",
	);
